"""Worker-side PDF rendering bridge using isolated per-process PDFium instances."""

from __future__ import annotations

import json
from pathlib import Path
import threading
from typing import Any

from PIL import Image

try:
    import pypdfium2 as pdfium
except ImportError:
    pdfium = None


_DOC_CACHE: dict[Path, Any] = {}
_META_CACHE: dict[Path, dict[str, Any]] = {}
_BRIDGE_LOCK = threading.Lock()


def load_pdf_metadata(metadata_path: Path) -> dict[str, Any] | None:
    """Load and cache PDF metadata generated by PdfBookshelf."""
    metadata_path = metadata_path.resolve()
    with _BRIDGE_LOCK:
        if metadata_path in _META_CACHE:
            return _META_CACHE[metadata_path]
    try:
        with open(metadata_path, encoding="utf-8") as file:
            data = json.load(file)
        with _BRIDGE_LOCK:
            _META_CACHE[metadata_path] = data
        return data
    except Exception:
        return None


def get_cached_document(pdf_path: Path) -> Any | None:
    """Get or open a cached PdfDocument for the calling process."""
    if pdfium is None:
        return None
    pdf_path = pdf_path.resolve()
    with _BRIDGE_LOCK:
        if pdf_path in _DOC_CACHE:
            return _DOC_CACHE[pdf_path]
    try:
        doc = pdfium.PdfDocument(pdf_path)
        with _BRIDGE_LOCK:
            _DOC_CACHE[pdf_path] = doc
        return doc
    except Exception:
        return None


def close_cached_documents() -> None:
    """Release all cached PDF documents in this process."""
    with _BRIDGE_LOCK:
        for doc in _DOC_CACHE.values():
            try:
                doc.close()
            except Exception:
                pass
        _DOC_CACHE.clear()
        _META_CACHE.clear()


def render_pdf_region_from_metadata(
    metadata_path: Path,
    page_index: int,
    source_box: tuple[float, float, float, float],
    target_size: tuple[int, int],
    resample: Image.Resampling = Image.Resampling.BICUBIC,
) -> Image.Image | None:
    """Render a cropped PDF page region in the current process using its own PDFium instance."""
    meta = load_pdf_metadata(metadata_path)
    if not meta:
        return None
    raw_pdf_path = meta.get("pdf_path")
    if not raw_pdf_path:
        return None
    pdf_path = Path(raw_pdf_path)
    scale = float(meta.get("scale", 1.5))

    doc = get_cached_document(pdf_path)
    if doc is None:
        return None

    try:
        page_count = len(doc)
    except Exception:
        return None

    if page_index < 0 or page_index >= page_count:
        return None

    target_width, target_height = target_size
    if target_width < 1 or target_height < 1:
        return None

    pages_meta = meta.get("pages", [])
    if page_index < len(pages_meta):
        native_width = int(pages_meta[page_index]["width"])
        native_height = int(pages_meta[page_index]["height"])
    else:
        try:
            w_pt, h_pt = doc.get_page_size(page_index)
            native_width = max(1, round(w_pt * scale))
            native_height = max(1, round(h_pt * scale))
        except Exception:
            return None

    left, top, right, bottom = source_box
    left = min(max(left, 0.0), float(native_width))
    right = min(max(right, left), float(native_width))
    top = min(max(top, 0.0), float(native_height))
    bottom = min(max(bottom, top), float(native_height))

    if right <= left or bottom <= top:
        return None

    render_scale = scale * target_width / (right - left)
    crop = (
        left / scale,
        (native_height - bottom) / scale,
        (native_width - right) / scale,
        top / scale,
    )

    try:
        page = doc[page_index]
        try:
            bitmap = page.render(
                scale=render_scale,
                crop=crop,
                limit_image_cache=True,
                rev_byteorder=True,
            )
            try:
                shared = bitmap.to_pil()
                try:
                    rendered = shared.convert("RGB")
                finally:
                    shared.close()
            finally:
                bitmap.close()
        finally:
            page.close()
    except Exception:
        return None

    if rendered.size != target_size:
        corrected = rendered.resize(target_size, resample=resample)
        rendered.close()
        rendered = corrected
    rendered.load()
    return rendered
